[package]
name = "slack-up"
version = "0.1.0"
authors = ["Jonathon Belotti <jonathon.bel.melbourne@gmail.com>"]
edition = "2018"

[dependencies]
github-rs = "0.7"
serde_json = "1.0"
structopt = "0.2.10"

[dev-dependencies]
assert_cmd = "0.10"
predicates = "1"
